// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyCFSKL5EbLXSw-0lrV2f1FmpPo9mDAkpfc',
    appId: '1:1094849136357:web:672cd7d5b8c33c8ff7760c',
    messagingSenderId: '1094849136357',
    projectId: 'first-app-e9e4c',
    authDomain: 'first-app-e9e4c.firebaseapp.com',
    databaseURL: 'https://first-app-e9e4c-default-rtdb.firebaseio.com',
    storageBucket: 'first-app-e9e4c.appspot.com',
    measurementId: 'G-5DZ7Z9T6FR',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyCwEvkyitE9hxr63seMUte6NvYSILOOVss',
    appId: '1:1094849136357:android:46934c9b296e6e66f7760c',
    messagingSenderId: '1094849136357',
    projectId: 'first-app-e9e4c',
    databaseURL: 'https://first-app-e9e4c-default-rtdb.firebaseio.com',
    storageBucket: 'first-app-e9e4c.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyCyFFeecG1YfFxyf9RKqENvJsLH8J_KCxE',
    appId: '1:1094849136357:ios:4edeb48d5da5d73ef7760c',
    messagingSenderId: '1094849136357',
    projectId: 'first-app-e9e4c',
    databaseURL: 'https://first-app-e9e4c-default-rtdb.firebaseio.com',
    storageBucket: 'first-app-e9e4c.appspot.com',
    iosBundleId: 'com.example.fasum',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyCyFFeecG1YfFxyf9RKqENvJsLH8J_KCxE',
    appId: '1:1094849136357:ios:96370bbe82092ba3f7760c',
    messagingSenderId: '1094849136357',
    projectId: 'first-app-e9e4c',
    databaseURL: 'https://first-app-e9e4c-default-rtdb.firebaseio.com',
    storageBucket: 'first-app-e9e4c.appspot.com',
    iosBundleId: 'com.example.fasum.RunnerTests',
  );
}
